### ISSUE TITLE
util的文件分类

### ISSUE THREAD

**Issue by SHA-4096** [FIY-pc/BBingyan#24]
https://github.com/FIY-pc/BBingyan/blob/8db21d6599ce84b32a3320a6192f7b183bbf492c/internal/util/smtp.go#L11C1-L42C2

smtp.go里写的感觉应该是“向某个地址发送某些内容”的功能函数，这里发送capcha的功能写到capcha.go里会不会好一些

**Comment by FIY-pc** [comment]
已把所有关于captcha的函数整合进captcha.go里
